path = r"C:\Users\邓涛\Documents\New project 3\file-crypto\src\crypto.cpp"
with open(path, "r", encoding="utf-8") as f:
    content = f.read()

# Replace the backup key block with hex-encoded text version
old = '''    // --- Backup Key File (.bak) ---
    std::string bakPath = keyFilePath + ".bak";
    std::ofstream bkf(bakPath, std::ios::binary);
    if (bkf) {
        bkf.write("KEYFILE1", 8);
        bkf.write(reinterpret_cast<char*>(&version), 1);
        bkf.write(reinterpret_cast<char*>(salt), 16);
        bkf.write(reinterpret_cast<char*>(iv), AES256::BLOCK_SIZE);
        bkf.write(reinterpret_cast<char*>(keyHash.data()), SHA256::HASH_SIZE);
        bkf.write(reinterpret_cast<char*>(evenHalf), HALF_KEY_SIZE);
        bkf.write(reinterpret_cast<char*>(oddHalf), HALF_KEY_SIZE);
        bkf.close();
    }'''

new = '''    // --- Backup Key File (.bak) - Human-readable hex text ---
    std::string bakPath = keyFilePath + ".bak";
    std::ofstream bkf(bakPath);
    if (bkf) {
        auto toHex = [](const uint8_t* data, int len) -> std::string {
            static const char hex[] = "0123456789abcdef";
            std::string s;
            s.reserve(len * 2);
            for (int i = 0; i < len; ++i) {
                s += hex[data[i] >> 4];
                s += hex[data[i] & 0x0f];
            }
            return s;
        };
        bkf << "# File Crypto Key Backup\n";
        bkf << "# Generated by FileCrypto v2 (64-byte master key)\n";
        bkf << "# Keep this file safe - it can reconstruct your encryption key\n\n";
        bkf << "master_key=" << toHex(masterKey.data(), MASTER_KEY_SIZE) << "\n";
        bkf << "salt=" << toHex(salt, 16) << "\n";
        bkf << "iv=" << toHex(iv, AES256::BLOCK_SIZE) << "\n";
        bkf << "sha256=" << toHex(keyHash.data(), SHA256::HASH_SIZE) << "\n";
        bkf.close();
    }'''

content = content.replace(old, new)
with open(path, "w", encoding="utf-8") as f:
    f.write(content)
print("Backup key format changed to hex text with full 64-byte master key")
