import json, os

out = r"C:\Users\邓涛\Documents\New project 3\file-crypto\src\lang_data.json"

# Start fresh with all languages added via helper
langs = {}
def add(code, **kw):
    langs[code] = kw

# ==== Language 1-10 ====
add("en", TITLE="=== File Encryption/Decryption Tool ===", SELECT_LANG="--- Select Language ---", MAIN_MENU="--- Main Menu ---", ENCRYPT="1. Encrypt File", DECRYPT="2. Decrypt File", CHANGE_LANG="3. Change Language", EXIT="4. Exit", ENTER_CHOICE="Enter your choice: ", INVALID_CHOICE="Invalid choice!", INPUT_FILE="Input file path: ", OUTPUT_FILE="Output file path: ", ENTER_PASSWORD="Enter password: ", CONFIRM_PASSWORD="Confirm password: ", PASSWORD_MISMATCH="Passwords do not match!", ENC_SUCCESS="Encryption successful!", DEC_SUCCESS="Decryption successful!", ENC_FAILED="Encryption failed: ", DEC_FAILED="Decryption failed: ", FILE_NOT_FOUND="File not found!", WRONG_PASS="Wrong password or corrupted file!", CONFIG_SAVED="Config saved.", CONFIG_LOADED="Config loaded.", GOODBYE="Goodbye!", PRESS_ENTER="Press Enter to continue...", ERROR_PREFIX="Error", LANG_PROMPT="Language number (1-50): ", ENC_PROMPT="Encrypt", DEC_PROMPT="Decrypt", CONTACT_INFO="Contact: WeChat forever870422 / Email 810372789@qq.com", WELCOME_CONTRIB="Help translate! Contact forever870422")
add("zh-CN", TITLE="=== 文件加密/解密工具 ===", SELECT_LANG="--- 选择语言 ---", MAIN_MENU="--- 主菜单 ---", ENCRYPT="1. 加密文件", DECRYPT="2. 解密文件", CHANGE_LANG="3. 切换语言", EXIT="4. 退出", ENTER_CHOICE="请输入选项：", INVALID_CHOICE="无效选项！", INPUT_FILE="输入文件路径：", OUTPUT_FILE="输出文件路径：", ENTER_PASSWORD="请输入密码：", CONFIRM_PASSWORD="请确认密码：", PASSWORD_MISMATCH="两次密码不一致！", ENC_SUCCESS="加密成功！", DEC_SUCCESS="解密成功！", ENC_FAILED="加密失败：", DEC_FAILED="解密失败：", FILE_NOT_FOUND="文件未找到！", WRONG_PASS="密码错误或文件损坏！", CONFIG_SAVED="配置已保存。", CONFIG_LOADED="配置已加载。", GOODBYE="再见！", PRESS_ENTER="按回车键继续...", ERROR_PREFIX="错误", LANG_PROMPT="语言编号 (1-50)：", ENC_PROMPT="加密", DEC_PROMPT="解密", CONTACT_INFO="联系方式: 微信 forever870422 / 邮箱 810372789@qq.com", WELCOME_CONTRIB="欢迎贡献翻译！联系 forever870422")
add("zh-TW", TITLE="=== 檔案加密/解密工具 ===", SELECT_LANG="--- 選擇語言 ---", MAIN_MENU="--- 主選單 ---", ENCRYPT="1. 加密檔案", DECRYPT="2. 解密檔案", CHANGE_LANG="3. 切換語言", EXIT="4. 退出", ENTER_CHOICE="請輸入選項：", INVALID_CHOICE="無效選項！", INPUT_FILE="輸入檔案路徑：", OUTPUT_FILE="輸出檔案路徑：", ENTER_PASSWORD="請輸入密碼：", CONFIRM_PASSWORD="請確認密碼：", PASSWORD_MISMATCH="兩次密碼不一致！", ENC_SUCCESS="加密成功！", DEC_SUCCESS="解密成功！", ENC_FAILED="加密失敗：", DEC_FAILED="解密失敗：", FILE_NOT_FOUND="檔案未找到！", WRONG_PASS="密碼錯誤或檔案損壞！", CONFIG_SAVED="配置已儲存。", CONFIG_LOADED="配置已載入。", GOODBYE="再見！", PRESS_ENTER="按Enter鍵繼續...", ERROR_PREFIX="錯誤", LANG_PROMPT="語言編號 (1-50)：", ENC_PROMPT="加密", DEC_PROMPT="解密", CONTACT_INFO="聯繫方式: 微信 forever870422 / 郵箱 810372789@qq.com", WELCOME_CONTRIB="歡迎貢獻翻譯！聯繫 forever870422")
add("es", TITLE="=== Herramienta de Cifrado ===", SELECT_LANG="--- Seleccionar Idioma ---", MAIN_MENU="--- Menu Principal ---", ENCRYPT="1. Cifrar archivo", DECRYPT="2. Descifrar archivo", CHANGE_LANG="3. Cambiar idioma", EXIT="4. Salir", ENTER_CHOICE="Ingrese opcion: ", INVALID_CHOICE="Opcion no valida!", INPUT_FILE="Ruta del archivo entrada: ", OUTPUT_FILE="Ruta del archivo salida: ", ENTER_PASSWORD="Ingrese contrasena: ", CONFIRM_PASSWORD="Confirme contrasena: ", PASSWORD_MISMATCH="Contrasenas no coinciden!", ENC_SUCCESS="Cifrado exitoso!", DEC_SUCCESS="Descifrado exitoso!", ENC_FAILED="Error de cifrado: ", DEC_FAILED="Error de descifrado: ", FILE_NOT_FOUND="Archivo no encontrado!", WRONG_PASS="Contrasena incorrecta o archivo danado!", CONFIG_SAVED="Configuracion guardada.", CONFIG_LOADED="Configuracion cargada.", GOODBYE="Adios!", PRESS_ENTER="Presione Enter...", ERROR_PREFIX="Error", LANG_PROMPT="Numero de idioma (1-50): ", ENC_PROMPT="Cifrar", DEC_PROMPT="Descifrar", CONTACT_INFO="Contacto: WeChat forever870422 / Email 810372789@qq.com", WELCOME_CONTRIB="Ayude a traducir! forever870422")
add("fr", TITLE="=== Outil de Chiffrement ===", SELECT_LANG="--- Choisir la langue ---", MAIN_MENU="--- Menu Principal ---", ENCRYPT="1. Chiffrer un fichier", DECRYPT="2. Dechiffrer un fichier", CHANGE_LANG="3. Changer de langue", EXIT="4. Quitter", ENTER_CHOICE="Entrez votre choix : ", INVALID_CHOICE="Choix invalide !", INPUT_FILE="Chemin du fichier source : ", OUTPUT_FILE="Chemin du fichier sortie : ", ENTER_PASSWORD="Mot de passe : ", CONFIRM_PASSWORD="Confirmer mot de passe : ", PASSWORD_MISMATCH="Mots de passe non concordants !", ENC_SUCCESS="Chiffrement reussi !", DEC_SUCCESS="Dechiffrement reussi !", ENC_FAILED="Echec du chiffrement : ", DEC_FAILED="Echec du dechiffrement : ", FILE_NOT_FOUND="Fichier introuvable !", WRONG_PASS="Mot de passe incorrect ou fichier corrompu !", CONFIG_SAVED="Configuration enregistree.", CONFIG_LOADED="Configuration chargee.", GOODBYE="Au revoir !", PRESS_ENTER="Appuyez sur Entree...", ERROR_PREFIX="Erreur", LANG_PROMPT="Numero de langue (1-50) : ", ENC_PROMPT="Chiffrer", DEC_PROMPT="Dechiffrer", CONTACT_INFO="Contact: WeChat forever870422 / Email 810372789@qq.com", WELCOME_CONTRIB="Aidez a traduire! forever870422")
add("de", TITLE="=== Datei-Verschluesselung ===", SELECT_LANG="--- Sprache waehlen ---", MAIN_MENU="--- Hauptmenue ---", ENCRYPT="1. Datei verschluesseln", DECRYPT="2. Datei entschluesseln", CHANGE_LANG="3. Sprache aendern", EXIT="4. Beenden", ENTER_CHOICE="Auswahl eingeben: ", INVALID_CHOICE="Ungueltige Auswahl!", INPUT_FILE="Eingabedatei: ", OUTPUT_FILE="Ausgabedatei: ", ENTER_PASSWORD="Passwort: ", CONFIRM_PASSWORD="Passwort bestaetigen: ", PASSWORD_MISMATCH="Passwoerter stimmen nicht ueberein!", ENC_SUCCESS="Verschluesselung erfolgreich!", DEC_SUCCESS="Entschluesselung erfolgreich!", ENC_FAILED="Verschluesselung fehlgeschlagen: ", DEC_FAILED="Entschluesselung fehlgeschlagen: ", FILE_NOT_FOUND="Datei nicht gefunden!", WRONG_PASS="Falsches Passwort oder beschaedigte Datei!", CONFIG_SAVED="Konfiguration gespeichert.", CONFIG_LOADED="Konfiguration geladen.", GOODBYE="Auf Wiedersehen!", PRESS_ENTER="Enter druecken...", ERROR_PREFIX="Fehler", LANG_PROMPT="Sprachnummer (1-50): ", ENC_PROMPT="Verschluesseln", DEC_PROMPT="Entschluesseln", CONTACT_INFO="Kontakt: WeChat forever870422 / Email 810372789@qq.com", WELCOME_CONTRIB="Hilf beim Uebersetzen! forever870422")
add("ja", TITLE="=== ファイル暗号化・復号ツール ===", SELECT_LANG="--- 言語を選択 ---", MAIN_MENU="--- メインメニュー ---", ENCRYPT="1. ファイルを暗号化", DECRYPT="2. ファイルを復号", CHANGE_LANG="3. 言語を変更", EXIT="4. 終了", ENTER_CHOICE="選択肢を入力：", INVALID_CHOICE="無効な選択です！", INPUT_FILE="入力ファイル：", OUTPUT_FILE="出力ファイル：", ENTER_PASSWORD="パスワード：", CONFIRM_PASSWORD="パスワード確認：", PASSWORD_MISMATCH="パスワードが一致しません！", ENC_SUCCESS="暗号化が成功しました！", DEC_SUCCESS="復号が成功しました！", ENC_FAILED="暗号化に失敗：", DEC_FAILED="復号に失敗：", FILE_NOT_FOUND="ファイルが見つかりません！", WRONG_PASS="パスワードが違うかファイルが壊れています！", CONFIG_SAVED="設定を保存しました。", CONFIG_LOADED="設定を読み込みました。", GOODBYE="さようなら！", PRESS_ENTER="Enterキーを押してください...", ERROR_PREFIX="エラー", LANG_PROMPT="言語番号 (1-50)：", ENC_PROMPT="暗号化", DEC_PROMPT="復号", CONTACT_INFO="連絡先: WeChat forever870422 / Email 810372789@qq.com", WELCOME_CONTRIB="翻訳協力募集中！forever870422")
add("ko", TITLE="=== 파일 암호화/복호화 도구 ===", SELECT_LANG="--- 언어 선택 ---", MAIN_MENU="--- 메인 메뉴 ---", ENCRYPT="1. 파일 암호화", DECRYPT="2. 파일 복호화", CHANGE_LANG="3. 언어 변경", EXIT="4. 종료", ENTER_CHOICE="선택 입력: ", INVALID_CHOICE="잘못된 선택!", INPUT_FILE="입력 파일: ", OUTPUT_FILE="출력 파일: ", ENTER_PASSWORD="비밀번호: ", CONFIRM_PASSWORD="비밀번호 확인: ", PASSWORD_MISMATCH="비밀번호가 일치하지 않습니다!", ENC_SUCCESS="암호화 성공!", DEC_SUCCESS="복호화 성공!", ENC_FAILED="암호화 실패: ", DEC_FAILED="복호화 실패: ", FILE_NOT_FOUND="파일을 찾을 수 없습니다!", WRONG_PASS="잘못된 비밀번호 또는 손상된 파일!", CONFIG_SAVED="설정이 저장되었습니다.", CONFIG_LOADED="설정이 로드되었습니다.", GOODBYE="안녕히 가세요!", PRESS_ENTER="Enter 키를 누르세요...", ERROR_PREFIX="오류", LANG_PROMPT="언어 번호 (1-50): ", ENC_PROMPT="암호화", DEC_PROMPT="복호화", CONTACT_INFO="연락처: WeChat forever870422 / Email 810372789@qq.com", WELCOME_CONTRIB="번역 기여 환영! forever870422")
add("ru", TITLE="=== Инструмент шифрования ===", SELECT_LANG="--- Выбор языка ---", MAIN_MENU="--- Главное меню ---", ENCRYPT="1. Зашифровать файл", DECRYPT="2. Расшифровать файл", CHANGE_LANG="3. Сменить язык", EXIT="4. Выход", ENTER_CHOICE="Введите выбор: ", INVALID_CHOICE="Неверный выбор!", INPUT_FILE="Исходный файл: ", OUTPUT_FILE="Выходной файл: ", ENTER_PASSWORD="Пароль: ", CONFIRM_PASSWORD="Подтвердите пароль: ", PASSWORD_MISMATCH="Пароли не совпадают!", ENC_SUCCESS="Шифрование успешно!", DEC_SUCCESS="Расшифровка успешна!", ENC_FAILED="Ошибка шифрования: ", DEC_FAILED="Ошибка расшифровки: ", FILE_NOT_FOUND="Файл не найден!", WRONG_PASS="Неверный пароль или файл поврежден!", CONFIG_SAVED="Конфигурация сохранена.", CONFIG_LOADED="Конфигурация загружена.", GOODBYE="До свидания!", PRESS_ENTER="Нажмите Enter...", ERROR_PREFIX="Ошибка", LANG_PROMPT="Номер языка (1-50): ", ENC_PROMPT="Шифровать", DEC_PROMPT="Расшифровать", CONTACT_INFO="Контакт: WeChat forever870422 / Email 810372789@qq.com", WELCOME_CONTRIB="Помогите с переводом! forever870422")
add("ar", TITLE="=== أداة تشفير/فك تشفير الملفات ===", SELECT_LANG="--- اختر اللغة ---", MAIN_MENU="--- القائمة الرئيسية ---", ENCRYPT="1. تشفير ملف", DECRYPT="2. فك تشفير ملف", CHANGE_LANG="3. تغيير اللغة", EXIT="4. خروج", ENTER_CHOICE="أدخل اختيارك: ", INVALID_CHOICE="اختيار غير صالح!", INPUT_FILE="مسار الملف المدخل: ", OUTPUT_FILE="مسار الملف المخرج: ", ENTER_PASSWORD="كلمة المرور: ", CONFIRM_PASSWORD="تأكيد كلمة المرور: ", PASSWORD_MISMATCH="كلمات المرور غير متطابقة!", ENC_SUCCESS="تم التشفير بنجاح!", DEC_SUCCESS="تم فك التشفير بنجاح!", ENC_FAILED="فشل التشفير: ", DEC_FAILED="فشل فك التشفير: ", FILE_NOT_FOUND="الملف غير موجود!", WRONG_PASS="كلمة مرور خاطئة أو ملف تالف!", CONFIG_SAVED="تم حفظ الإعدادات.", CONFIG_LOADED="تم تحميل الإعدادات.", GOODBYE="وداعا!", PRESS_ENTER="اضغط Enter...", ERROR_PREFIX="خطأ", LANG_PROMPT="رقم اللغة (1-50): ", ENC_PROMPT="تشفير", DEC_PROMPT="فك تشفير", CONTACT_INFO="للتواصل: WeChat forever870422 / Email 810372789@qq.com", WELCOME_CONTRIB="مساهمات الترجمة مرحب بها! forever870422")

with open(out, 'w', encoding='utf-8') as f:
    json.dump(langs, f, ensure_ascii=False, indent=2)
print(f"Saved {len(langs)} languages to lang_data.json")
