import json
path = r"C:\Users\邓涛\Documents\New project 3\file-crypto\src\lang_data.json"
with open(path, 'r', encoding='utf-8') as f:
    langs = json.load(f)
def add(code, **kw):
    langs[code] = kw

add("da", TITLE="=== Filkrypteringsvaerktoj ===", SELECT_LANG="--- Vaelg sprog ---", MAIN_MENU="--- Hovedmenu ---", ENCRYPT="1. Krypter fil", DECRYPT="2. Dekrypter fil", CHANGE_LANG="3. Skift sprog", EXIT="4. Afslut", ENTER_CHOICE="Indtast valg: ", INVALID_CHOICE="Ugyldigt valg!", INPUT_FILE="Input fil: ", OUTPUT_FILE="Output fil: ", ENTER_PASSWORD="Adgangskode: ", CONFIRM_PASSWORD="Bekraeft adgangskode: ", PASSWORD_MISMATCH="Adgangskoder matcher ikke!", ENC_SUCCESS="Kryptering lykkedes!", DEC_SUCCESS="Dekryptering lykkedes!", ENC_FAILED="Kryptering mislykkedes: ", DEC_FAILED="Dekryptering mislykkedes: ", FILE_NOT_FOUND="Fil ikke fundet!", WRONG_PASS="Forkert adgangskode eller beskadiget fil!", CONFIG_SAVED="Konfiguration gemt.", CONFIG_LOADED="Konfiguration indlaest.", GOODBYE="Farvel!", PRESS_ENTER="Tryk Enter...", ERROR_PREFIX="Fejl", LANG_PROMPT="Sprognummer (1-50): ", ENC_PROMPT="Krypter", DEC_PROMPT="Dekrypter", CONTACT_INFO="Kontakt: WeChat forever870422 / Email 810372789@qq.com", WELCOME_CONTRIB="Hjaelp med oversaettelse! forever870422")
add("fi", TITLE="=== Tiedoston Salaus ===", SELECT_LANG="--- Valitse kieli ---", MAIN_MENU="--- Paavalikko ---", ENCRYPT="1. Salaa tiedosto", DECRYPT="2. Pura salaus", CHANGE_LANG="3. Vaihda kielta", EXIT="4. Lopeta", ENTER_CHOICE="Anna valinta: ", INVALID_CHOICE="Virheellinen valinta!", INPUT_FILE="Syotetiedosto: ", OUTPUT_FILE="Tulostiedosto: ", ENTER_PASSWORD="Salasana: ", CONFIRM_PASSWORD="Vahvista salasana: ", PASSWORD_MISMATCH="Salasanat eivat taasmaa!", ENC_SUCCESS="Salaus onnistui!", DEC_SUCCESS="Salauksen purku onnistui!", ENC_FAILED="Salaus epaonnistui: ", DEC_FAILED="Salauksen purku epaonnistui: ", FILE_NOT_FOUND="Tiedostoa ei loydy!", WRONG_PASS="Vaara salasana tai vioittunut tiedosto!", CONFIG_SAVED="Asetukset tallennettu.", CONFIG_LOADED="Asetukset ladattu.", GOODBYE="Nakemiin!", PRESS_ENTER="Paina Enter...", ERROR_PREFIX="Virhe", LANG_PROMPT="Kielen numero (1-50): ", ENC_PROMPT="Salaa", DEC_PROMPT="Pura", CONTACT_INFO="Yhteystiedot: WeChat forever870422 / Email 810372789@qq.com", WELCOME_CONTRIB="Auta kaantamisessa! forever870422")
add("no", TITLE="=== Filkrypteringsverktoy ===", SELECT_LANG="--- Velg sprak ---", MAIN_MENU="--- Hovedmeny ---", ENCRYPT="1. Krypter fil", DECRYPT="2. Dekrypter fil", CHANGE_LANG="3. Bytt sprak", EXIT="4. Avslutt", ENTER_CHOICE="Skriv inn valg: ", INVALID_CHOICE="Ugyldig valg!", INPUT_FILE="Innfil: ", OUTPUT_FILE="Utfil: ", ENTER_PASSWORD="Passord: ", CONFIRM_PASSWORD="Bekreft passord: ", PASSWORD_MISMATCH="Passordene stemmer ikke!", ENC_SUCCESS="Kryptering vellykket!", DEC_SUCCESS="Dekryptering vellykket!", ENC_FAILED="Kryptering mislyktes: ", DEC_FAILED="Dekryptering mislyktes: ", FILE_NOT_FOUND="Fil ikke funnet!", WRONG_PASS="Feil passord eller odelagt fil!", CONFIG_SAVED="Konfigurasjon lagret.", CONFIG_LOADED="Konfigurasjon lastet.", GOODBYE="Ha det!", PRESS_ENTER="Trykk Enter...", ERROR_PREFIX="Feil", LANG_PROMPT="Spraknummer (1-50): ", ENC_PROMPT="Krypter", DEC_PROMPT="Dekrypter", CONTACT_INFO="Kontakt: WeChat forever870422 / Email 810372789@qq.com", WELCOME_CONTRIB="Hjelp med oversettelse! forever870422")
add("cs", TITLE="=== Sifrovani souboru ===", SELECT_LANG="--- Vyberte jazyk ---", MAIN_MENU="--- Hlavni menu ---", ENCRYPT="1. Zasifrovat soubor", DECRYPT="2. Desifrovat soubor", CHANGE_LANG="3. Zmenit jazyk", EXIT="4. Konec", ENTER_CHOICE="Zadejte volbu: ", INVALID_CHOICE="Neplatna volba!", INPUT_FILE="Vstupni soubor: ", OUTPUT_FILE="Vystupni soubor: ", ENTER_PASSWORD="Heslo: ", CONFIRM_PASSWORD="Potvrdit heslo: ", PASSWORD_MISMATCH="Hesla se neshoduji!", ENC_SUCCESS="Sifrovani uspesne!", DEC_SUCCESS="Desifrovani uspesne!", ENC_FAILED="Sifrovani selhalo: ", DEC_FAILED="Desifrovani selhalo: ", FILE_NOT_FOUND="Soubor nenalezen!", WRONG_PASS="Spatne heslo nebo poskozeny soubor!", CONFIG_SAVED="Konfigurace ulozena.", CONFIG_LOADED="Konfigurace nactena.", GOODBYE="Nashledanou!", PRESS_ENTER="Stisknete Enter...", ERROR_PREFIX="Chyba", LANG_PROMPT="Cislo jazyka (1-50): ", ENC_PROMPT="Sifrovat", DEC_PROMPT="Desifrovat", CONTACT_INFO="Kontakt: WeChat forever870422 / Email 810372789@qq.com", WELCOME_CONTRIB="Pomozte s prekladem! forever870422")
add("hu", TITLE="=== Fajltitkosito Eszkoz ===", SELECT_LANG="--- Valasszon nyelvet ---", MAIN_MENU="--- Fomenu ---", ENCRYPT="1. Fajl titkositasa", DECRYPT="2. Fajl visszafejtese", CHANGE_LANG="3. Nyelv valtasa", EXIT="4. Kilepes", ENTER_CHOICE="Valasztas: ", INVALID_CHOICE="Ervenytelen valasztas!", INPUT_FILE="Bemeneti fajl: ", OUTPUT_FILE="Kimeneti fajl: ", ENTER_PASSWORD="Jelszo: ", CONFIRM_PASSWORD="Jelszo megerosit: ", PASSWORD_MISMATCH="A jelszavak nem egyeznek!", ENC_SUCCESS="Titkositas sikeres!", DEC_SUCCESS="Visszafejtes sikeres!", ENC_FAILED="Titkositas sikertelen: ", DEC_FAILED="Visszafejtes sikertelen: ", FILE_NOT_FOUND="A fajl nem talalhato!", WRONG_PASS="Hibas jelszo vagy serult fajl!", CONFIG_SAVED="Konfiguracio mentve.", CONFIG_LOADED="Konfiguracio betoltve.", GOODBYE="Viszontlatasra!", PRESS_ENTER="Nyomjon Entert...", ERROR_PREFIX="Hiba", LANG_PROMPT="Nyelv szama (1-50): ", ENC_PROMPT="Titkosit", DEC_PROMPT="Visszafejt", CONTACT_INFO="Kapcsolat: WeChat forever870422 / Email 810372789@qq.com", WELCOME_CONTRIB="Segitsen forditani! forever870422")
add("ro", TITLE="=== Instrument Criptare ===", SELECT_LANG="--- Selectati limba ---", MAIN_MENU="--- Meniu Principal ---", ENCRYPT="1. Criptare fisier", DECRYPT="2. Decriptare fisier", CHANGE_LANG="3. Schimba limba", EXIT="4. Iesire", ENTER_CHOICE="Introduceti optiunea: ", INVALID_CHOICE="Optiune invalida!", INPUT_FILE="Fisier intrare: ", OUTPUT_FILE="Fisier iesire: ", ENTER_PASSWORD="Parola: ", CONFIRM_PASSWORD="Confirmati parola: ", PASSWORD_MISMATCH="Parolele nu coincid!", ENC_SUCCESS="Criptare reusita!", DEC_SUCCESS="Decriptare reusita!", ENC_FAILED="Criptare esuata: ", DEC_FAILED="Decriptare esuata: ", FILE_NOT_FOUND="Fisierul nu a fost gasit!", WRONG_PASS="Parola gresita sau fisier corupt!", CONFIG_SAVED="Configuratie salvata.", CONFIG_LOADED="Configuratie incarcata.", GOODBYE="La revedere!", PRESS_ENTER="Apasati Enter...", ERROR_PREFIX="Eroare", LANG_PROMPT="Numar limba (1-50): ", ENC_PROMPT="Criptare", DEC_PROMPT="Decriptare", CONTACT_INFO="Contact: WeChat forever870422 / Email 810372789@qq.com", WELCOME_CONTRIB="Ajutati la traducere! forever870422")
add("el", TITLE="=== Εργαλείο Κρυπτογράφησης ===", SELECT_LANG="--- Επιλέξτε γλώσσα ---", MAIN_MENU="--- Βασικό Μενού ---", ENCRYPT="1. Κρυπτογράφηση αρχείου", DECRYPT="2. Αποκρυπτογράφηση", CHANGE_LANG="3. Αλλαγή γλώσσας", EXIT="4. Έξοδος", ENTER_CHOICE="Εισάγετε επιλογή: ", INVALID_CHOICE="Μη έγκυρη επιλογή!", INPUT_FILE="Αρχείο εισόδου: ", OUTPUT_FILE="Αρχείο εξόδου: ", ENTER_PASSWORD="Κωδικός: ", CONFIRM_PASSWORD="Επιβεβαίωση κωδικού: ", PASSWORD_MISMATCH="Οι κωδικοί δεν ταιριάζουν!", ENC_SUCCESS="Κρυπτογράφηση επιτυχής!", DEC_SUCCESS="Αποκρυπτογράφηση επιτυχής!", ENC_FAILED="Κρυπτογράφηση απέτυχε: ", DEC_FAILED="Αποκρυπτογράφηση απέτυχε: ", FILE_NOT_FOUND="Το αρχείο δεν βρέθηκε!", WRONG_PASS="Λάθος κωδικός ή κατεστραμμένο αρχείο!", CONFIG_SAVED="Η ρύθμιση αποθηκεύτηκε.", CONFIG_LOADED="Η ρύθμιση φορτώθηκε.", GOODBYE="Αντίο!", PRESS_ENTER="Πατήστε Enter...", ERROR_PREFIX="Σφάλμα", LANG_PROMPT="Αριθμός γλώσσας (1-50): ", ENC_PROMPT="Κρυπτογράφηση", DEC_PROMPT="Αποκρυπτογράφηση", CONTACT_INFO="Επικοινωνία: WeChat forever870422 / Email 810372789@qq.com", WELCOME_CONTRIB="Βοηθήστε στη μετάφραση! forever870422")
add("he", TITLE="=== כלי הצפנת קבצים ===", SELECT_LANG="--- בחר שפה ---", MAIN_MENU="--- תפריט ראשי ---", ENCRYPT="1. הצפן קובץ", DECRYPT="2. פענח קובץ", CHANGE_LANG="3. החלף שפה", EXIT="4. יציאה", ENTER_CHOICE="הזן בחירה: ", INVALID_CHOICE="בחירה לא חוקית!", INPUT_FILE="נתיב קובץ קלט: ", OUTPUT_FILE="נתיב קובץ פלט: ", ENTER_PASSWORD="סיסמה: ", CONFIRM_PASSWORD="אשר סיסמה: ", PASSWORD_MISMATCH="הסיסמאות אינן תואמות!", ENC_SUCCESS="ההצפנה הצליחה!", DEC_SUCCESS="הפענוח הצליח!", ENC_FAILED="ההצפנה נכשלה: ", DEC_FAILED="הפענוח נכשל: ", FILE_NOT_FOUND="הקובץ לא נמצא!", WRONG_PASS="סיסמה שגויה או קובץ פגום!", CONFIG_SAVED="ההגדרות נשמרו.", CONFIG_LOADED="ההגדרות נטענו.", GOODBYE="להתראות!", PRESS_ENTER="לחץ Enter...", ERROR_PREFIX="שגיאה", LANG_PROMPT="מספר שפה (1-50): ", ENC_PROMPT="הצפן", DEC_PROMPT="פענח", CONTACT_INFO="צור קשר: WeChat forever870422 / Email 810372789@qq.com", WELCOME_CONTRIB="עזור לתרגם! forever870422")
add("id", TITLE="=== Alat Enkripsi/Dekripsi ===", SELECT_LANG="--- Pilih Bahasa ---", MAIN_MENU="--- Menu Utama ---", ENCRYPT="1. Enkripsi file", DECRYPT="2. Dekripsi file", CHANGE_LANG="3. Ganti bahasa", EXIT="4. Keluar", ENTER_CHOICE="Masukkan pilihan: ", INVALID_CHOICE="Pilihan tidak valid!", INPUT_FILE="File masukan: ", OUTPUT_FILE="File keluaran: ", ENTER_PASSWORD="Kata sandi: ", CONFIRM_PASSWORD="Konfirmasi kata sandi: ", PASSWORD_MISMATCH="Kata sandi tidak cocok!", ENC_SUCCESS="Enkripsi berhasil!", DEC_SUCCESS="Dekripsi berhasil!", ENC_FAILED="Enkripsi gagal: ", DEC_FAILED="Dekripsi gagal: ", FILE_NOT_FOUND="File tidak ditemukan!", WRONG_PASS="Kata sandi salah atau file rusak!", CONFIG_SAVED="Konfigurasi disimpan.", CONFIG_LOADED="Konfigurasi dimuat.", GOODBYE="Selamat tinggal!", PRESS_ENTER="Tekan Enter...", ERROR_PREFIX="Kesalahan", LANG_PROMPT="Nomor bahasa (1-50): ", ENC_PROMPT="Enkripsi", DEC_PROMPT="Dekripsi", CONTACT_INFO="Kontak: WeChat forever870422 / Email 810372789@qq.com", WELCOME_CONTRIB="Bantu terjemahan! forever870422")
add("ms", TITLE="=== Alat Penyulitan ===", SELECT_LANG="--- Pilih Bahasa ---", MAIN_MENU="--- Menu Utama ---", ENCRYPT="1. Sulitkan fail", DECRYPT="2. Nyahsulit fail", CHANGE_LANG="3. Tukar bahasa", EXIT="4. Keluar", ENTER_CHOICE="Masukkan pilihan: ", INVALID_CHOICE="Pilihan tidak sah!", INPUT_FILE="Fail input: ", OUTPUT_FILE="Fail output: ", ENTER_PASSWORD="Kata laluan: ", CONFIRM_PASSWORD="Sahkan kata laluan: ", PASSWORD_MISMATCH="Kata laluan tidak sepadan!", ENC_SUCCESS="Penyulitan berjaya!", DEC_SUCCESS="Nyahsulit berjaya!", ENC_FAILED="Penyulitan gagal: ", DEC_FAILED="Nyahsulit gagal: ", FILE_NOT_FOUND="Fail tidak dijumpai!", WRONG_PASS="Kata laluan salah atau fail rosak!", CONFIG_SAVED="Konfigurasi disimpan.", CONFIG_LOADED="Konfigurasi dimuatkan.", GOODBYE="Selamat tinggal!", PRESS_ENTER="Tekan Enter...", ERROR_PREFIX="Ralat", LANG_PROMPT="Nombor bahasa (1-50): ", ENC_PROMPT="Sulitkan", DEC_PROMPT="Nyahsulit", CONTACT_INFO="Hubungi: WeChat forever870422 / Email 810372789@qq.com", WELCOME_CONTRIB="Bantu terjemahan! forever870422")

with open(path, 'w', encoding='utf-8') as f:
    json.dump(langs, f, ensure_ascii=False, indent=2)
print(f"Now have {len(langs)} languages")
