import json
path = r"C:\Users\邓涛\Documents\New project 3\file-crypto\src\lang_data.json"
with open(path, 'r', encoding='utf-8') as f:
    langs = json.load(f)
def add(code, **kw):
    langs[code] = kw

add("km", TITLE="=== ឧបករណ៍អ៊ិនគ្រីបឯកសារ ===", SELECT_LANG="--- ជ្រើសរើសភាសា ---", MAIN_MENU="--- ម៉ឺនុយចម្បង ---", ENCRYPT="1. អ៊ិនគ្រីបឯកសារ", DECRYPT="2. ឌិគ្រីបឯកសារ", CHANGE_LANG="3. ប្តូរភាសា", EXIT="4. ចាកចេញ", ENTER_CHOICE="បញ្ចូលជម្រើស: ", INVALID_CHOICE="ជម្រើសមិនត្រឹមត្រូវ!", INPUT_FILE="ឯកសារបញ្ចូល: ", OUTPUT_FILE="ឯកសារលទ្ធផល: ", ENTER_PASSWORD="ពាក្យសម្ងាត់: ", CONFIRM_PASSWORD="បញ្ជាក់ពាក្យសម្ងាត់: ", PASSWORD_MISMATCH="ពាក្យសម្ងាត់មិនត្រូវគ្នា!", ENC_SUCCESS="អ៊ិនគ្រីបជោគជ័យ!", DEC_SUCCESS="ឌិគ្រីបជោគជ័យ!", ENC_FAILED="អ៊ិនគ្រីបបរាជ័យ: ", DEC_FAILED="ឌិគ្រីបបរាជ័យ: ", FILE_NOT_FOUND="រកមិនឃើញឯកសារ!", WRONG_PASS="ពាក្យសម្ងាត់ខុសឬឯកសារខូច!", CONFIG_SAVED="ការកំណត់បានរក្សាទុក។", CONFIG_LOADED="ការកំណត់បានផ្ទុក។", GOODBYE="លាហើយ!", PRESS_ENTER="ចុច Enter ដើម្បីបន្ត...", ERROR_PREFIX="កំហុស", LANG_PROMPT="លេខភាសា (1-50): ", ENC_PROMPT="អ៊ិនគ្រីប", DEC_PROMPT="ឌិគ្រីប", CONTACT_INFO="ទំនាក់ទំនង: WeChat forever870422 / Email 810372789@qq.com", WELCOME_CONTRIB="ជួយបកប្រែ! forever870422")
add("lo", TITLE="=== ເຄື່ອງມືເຂົ້າລະຫັດ ===", SELECT_LANG="--- ເລືອກພາສາ ---", MAIN_MENU="--- ເມນູຫຼັກ ---", ENCRYPT="1. ເຂົ້າລະຫັດໄຟລ໌", DECRYPT="2. ຖອດລະຫັດໄຟລ໌", CHANGE_LANG="3. ປ່ຽນພາສາ", EXIT="4. ອອກ", ENTER_CHOICE="ໃສ່ທາງເລືອກ: ", INVALID_CHOICE="ທາງເລືອກບໍ່ຖືກຕ້ອງ!", INPUT_FILE="ໄຟລ໌ປ້ອນເຂົ້າ: ", OUTPUT_FILE="ໄຟລ໌ຜົນອອກ: ", ENTER_PASSWORD="ລະຫັດຜ່ານ: ", CONFIRM_PASSWORD="ຢືນຢັນລະຫັດຜ່ານ: ", PASSWORD_MISMATCH="ລະຫັດຜ່ານບໍ່ກົງກັນ!", ENC_SUCCESS="ເຂົ້າລະຫັດສຳເລັດ!", DEC_SUCCESS="ຖອດລະຫັດສຳເລັດ!", ENC_FAILED="ເຂົ້າລະຫັດລົ້ມເຫລວ: ", DEC_FAILED="ຖອດລະຫັດລົ້ມເຫລວ: ", FILE_NOT_FOUND="ບໍ່ພົບໄຟລ໌!", WRONG_PASS="ລະຫັດຜ່ານຜິດຫຼືໄຟລ໌ເສຍຫາຍ!", CONFIG_SAVED="ບັນທຶກການຕັ້ງຄ່າແລ້ວ.", CONFIG_LOADED="ໂຫລດການຕັ້ງຄ່າແລ້ວ.", GOODBYE="ລາກ່ອນ!", PRESS_ENTER="ກົດ Enter ເພື່ອສືບຕໍ່...", ERROR_PREFIX="ຂໍ້ຜິດພາດ", LANG_PROMPT="ເລກພາສາ (1-50): ", ENC_PROMPT="ເຂົ້າລະຫັດ", DEC_PROMPT="ຖອດລະຫັດ", CONTACT_INFO="ຕິດຕໍ່: WeChat forever870422 / Email 810372789@qq.com", WELCOME_CONTRIB="ຊ່ວຍແປພາສາ! forever870422")
add("ne", TITLE="=== फाइल इन्क्रिप्सन उपकरण ===", SELECT_LANG="--- भाषा छान्नुहोस् ---", MAIN_MENU="--- मुख्य मेनु ---", ENCRYPT="1. फाइल इन्क्रिप्ट गर्नुहोस्", DECRYPT="2. फाइल डिक्रिप्ट गर्नुहोस्", CHANGE_LANG="3. भाषा परिवर्तन गर्नुहोस्", EXIT="4. बाहिरिनुहोस्", ENTER_CHOICE="आफ्नो छनौट प्रविष्ट गर्नुहोस्: ", INVALID_CHOICE="अवैध छनौट!", INPUT_FILE="इनपुट फाइल: ", OUTPUT_FILE="आउटपुट फाइल: ", ENTER_PASSWORD="पासवर्ड: ", CONFIRM_PASSWORD="पासवर्ड पुष्टि गर्नुहोस्: ", PASSWORD_MISMATCH="पासवर्डहरू मेल खाँदैनन्!", ENC_SUCCESS="इन्क्रिप्सन सफल!", DEC_SUCCESS="डिक्रिप्सन सफल!", ENC_FAILED="इन्क्रिप्सन असफल: ", DEC_FAILED="डिक्रिप्सन असफल: ", FILE_NOT_FOUND="फाइल फेला परेन!", WRONG_PASS="गलत पासवर्ड वा बिग्रिएको फाइल!", CONFIG_SAVED="कन्फिगरेसन सुरक्षित गरियो।", CONFIG_LOADED="कन्फिगरेसन लोड गरियो।", GOODBYE="अलविदा!", PRESS_ENTER="जारी राख्न Enter थिच्नुहोस्...", ERROR_PREFIX="त्रुटि", LANG_PROMPT="भाषा नम्बर (1-50): ", ENC_PROMPT="इन्क्रिप्ट", DEC_PROMPT="डिक्रिप्ट", CONTACT_INFO="सम्पर्क: WeChat forever870422 / Email 810372789@qq.com", WELCOME_CONTRIB="अनुवादमा मद्दत गर्नुहोस्! forever870422")
add("si", TITLE="=== ගොනු සංකේතන මෙවලම ===", SELECT_LANG="--- භාෂාව තෝරන්න ---", MAIN_MENU="--- ප්රධාන මෙනුව ---", ENCRYPT="1. ගොනුව සංකේතනය කරන්න", DECRYPT="2. ගොනුව විසංකේතනය කරන්න", CHANGE_LANG="3. භාෂාව වෙනස් කරන්න", EXIT="4. පිටවීම", ENTER_CHOICE="ඔබේ තේරීම ඇතුළත් කරන්න: ", INVALID_CHOICE="වලංගු නොවන තේරීම!", INPUT_FILE="ආදාන ගොනුව: ", OUTPUT_FILE="ප්රතිදාන ගොනුව: ", ENTER_PASSWORD="මුරපදය: ", CONFIRM_PASSWORD="මුරපදය තහවුරු කරන්න: ", PASSWORD_MISMATCH="මුරපද නොගැලපේ!", ENC_SUCCESS="සංකේතනය සාර්ථකයි!", DEC_SUCCESS="විසංකේතනය සාර්ථකයි!", ENC_FAILED="සංකේතනය අසාර්ථකයි: ", DEC_FAILED="විසංකේතනය අසාර්ථකයි: ", FILE_NOT_FOUND="ගොනුව හමු නොවීය!", WRONG_PASS="වැරදි මුරපදයක් හෝ දූෂිත ගොනුවක්!", CONFIG_SAVED="වින්යාසය සුරැකිණි.", CONFIG_LOADED="වින්යාසය පූරණය කරන ලදී.", GOODBYE="ආයුබෝවන්!", PRESS_ENTER="ඉදිරියට යාමට Enter ඔබන්න...", ERROR_PREFIX="දෝෂය", LANG_PROMPT="භාෂා අංකය (1-50): ", ENC_PROMPT="සංකේතනය", DEC_PROMPT="විසංකේතනය", CONTACT_INFO="සම්බන්ධතා: WeChat forever870422 / Email 810372789@qq.com", WELCOME_CONTRIB="පරිවර්තනයට උදව් කරන්න! forever870422")
add("am", TITLE="=== የፋይል ምስጠራ መሳሪያ ===", SELECT_LANG="--- ቋንቋ ይምረጡ ---", MAIN_MENU="--- ዋና ሜኑ ---", ENCRYPT="1. ፋይል ኢንክሪፕት አድርግ", DECRYPT="2. ፋይል ዲክሪፕት አድርግ", CHANGE_LANG="3. ቋንቋ ቀይር", EXIT="4. ውጣ", ENTER_CHOICE="ምርጫህን አስገባ: ", INVALID_CHOICE="ልክ ያልሆነ ምርጫ!", INPUT_FILE="የግቤት ፋይል: ", OUTPUT_FILE="የውጤት ፋይል: ", ENTER_PASSWORD="የይለፍ ቃል: ", CONFIRM_PASSWORD="የይለፍ ቃል አረጋግጥ: ", PASSWORD_MISMATCH="የይለፍ ቃላት አይዛመዱም!", ENC_SUCCESS="ምስጠራ ተሳክቷል!", DEC_SUCCESS="መፍታት ተሳክቷል!", ENC_FAILED="ምስጠራ አልተሳካም: ", DEC_FAILED="መፍታት አልተሳካም: ", FILE_NOT_FOUND="ፋይል አልተገኘም!", WRONG_PASS="የተሳሳተ የይለፍ ቃል ወይም የተበላሸ ፋይል!", CONFIG_SAVED="ውቅር ተቀምጧል።", CONFIG_LOADED="ውቅር ተጭኗል።", GOODBYE="ደህና ሁን!", PRESS_ENTER="ለመቀጠል Enter ይጫኑ...", ERROR_PREFIX="ስህተት", LANG_PROMPT="የቋንቋ ቁጥር (1-50): ", ENC_PROMPT="ኢንክሪፕት", DEC_PROMPT="ዲክሪፕት", CONTACT_INFO="አድራሻ: WeChat forever870422 / Email 810372789@qq.com", WELCOME_CONTRIB="በትርጉም ያግዙ! forever870422")
add("sw", TITLE="=== Zana ya Usimbaji ===", SELECT_LANG="--- Chagua Lugha ---", MAIN_MENU="--- Menyu Kuu ---", ENCRYPT="1. Simba faili", DECRYPT="2. Fumbua faili", CHANGE_LANG="3. Badilisha lugha", EXIT="4. Toka", ENTER_CHOICE="Ingiza chaguo: ", INVALID_CHOICE="Chaguo batili!", INPUT_FILE="Faili ya kuingiza: ", OUTPUT_FILE="Faili ya kutoa: ", ENTER_PASSWORD="Nenosiri: ", CONFIRM_PASSWORD="Thibitisha nenosiri: ", PASSWORD_MISMATCH="Manenosiri hayalingani!", ENC_SUCCESS="Usimbaji umefanikiwa!", DEC_SUCCESS="Ufumbuzi umefanikiwa!", ENC_FAILED="Usimbaji umeshindwa: ", DEC_FAILED="Ufumbuzi umeshindwa: ", FILE_NOT_FOUND="Faili haijapatikana!", WRONG_PASS="Nenosiri lisilo sahihi au faili imeharibika!", CONFIG_SAVED="Mipangilio imehifadhiwa.", CONFIG_LOADED="Mipangilio imepakiwa.", GOODBYE="Kwaheri!", PRESS_ENTER="Bonyeza Enter kuendelea...", ERROR_PREFIX="Hitilafu", LANG_PROMPT="Nambari ya lugha (1-50): ", ENC_PROMPT="Simba", DEC_PROMPT="Fumbua", CONTACT_INFO="Mawasiliano: WeChat forever870422 / Email 810372789@qq.com", WELCOME_CONTRIB="Saidia kutafsiri! forever870422")
add("fil", TITLE="=== Tool ng Pag-encrypt ===", SELECT_LANG="--- Pumili ng Wika ---", MAIN_MENU="--- Pangunahing Menu ---", ENCRYPT="1. I-encrypt ang file", DECRYPT="2. I-decrypt ang file", CHANGE_LANG="3. Palitan ang wika", EXIT="4. Lumabas", ENTER_CHOICE="Ilagay ang pinili: ", INVALID_CHOICE="Di-wastong pinili!", INPUT_FILE="Input file: ", OUTPUT_FILE="Output file: ", ENTER_PASSWORD="Password: ", CONFIRM_PASSWORD="Kumpirmahin ang password: ", PASSWORD_MISMATCH="Hindi tugma ang mga password!", ENC_SUCCESS="Matagumpay ang pag-encrypt!", DEC_SUCCESS="Matagumpay ang pag-decrypt!", ENC_FAILED="Nabigo ang pag-encrypt: ", DEC_FAILED="Nabigo ang pag-decrypt: ", FILE_NOT_FOUND="Hindi nakita ang file!", WRONG_PASS="Maling password o sirang file!", CONFIG_SAVED="Na-save ang configuration.", CONFIG_LOADED="Na-load ang configuration.", GOODBYE="Paalam!", PRESS_ENTER="Pindutin ang Enter...", ERROR_PREFIX="Error", LANG_PROMPT="Numero ng wika (1-50): ", ENC_PROMPT="I-encrypt", DEC_PROMPT="I-decrypt", CONTACT_INFO="Kontak: WeChat forever870422 / Email 810372789@qq.com", WELCOME_CONTRIB="Tumulong sa pagsasalin! forever870422")
add("sr", TITLE="=== Alat za Sifrovanje ===", SELECT_LANG="--- Izaberite jezik ---", MAIN_MENU="--- Glavni meni ---", ENCRYPT="1. Sifruj datoteku", DECRYPT="2. Desifruj datoteku", CHANGE_LANG="3. Promeni jezik", EXIT="4. Izlaz", ENTER_CHOICE="Unesite izbor: ", INVALID_CHOICE="Nevazeci izbor!", INPUT_FILE="Ulazna datoteka: ", OUTPUT_FILE="Izlazna datoteka: ", ENTER_PASSWORD="Lozinka: ", CONFIRM_PASSWORD="Potvrdite lozinku: ", PASSWORD_MISMATCH="Lozinke se ne poklapaju!", ENC_SUCCESS="Sifrovanje uspesno!", DEC_SUCCESS="Desifrovanje uspesno!", ENC_FAILED="Sifrovanje neuspesno: ", DEC_FAILED="Desifrovanje neuspesno: ", FILE_NOT_FOUND="Datoteka nije pronadjena!", WRONG_PASS="Pogresna lozinka ili ostecena datoteka!", CONFIG_SAVED="Konfiguracija sacuvana.", CONFIG_LOADED="Konfiguracija ucitana.", GOODBYE="Dovidjenja!", PRESS_ENTER="Pritisnite Enter...", ERROR_PREFIX="Greska", LANG_PROMPT="Broj jezika (1-50): ", ENC_PROMPT="Sifruj", DEC_PROMPT="Desifruj", CONTACT_INFO="Kontakt: WeChat forever870422 / Email 810372789@qq.com", WELCOME_CONTRIB="Pomozite u prevodu! forever870422")
add("hr", TITLE="=== Alat za Sifriranje ===", SELECT_LANG="--- Odaberite jezik ---", MAIN_MENU="--- Glavni izbornik ---", ENCRYPT="1. Sifriraj datoteku", DECRYPT="2. Desifriraj datoteku", CHANGE_LANG="3. Promijeni jezik", EXIT="4. Izlaz", ENTER_CHOICE="Unesite izbor: ", INVALID_CHOICE="Nevazeci izbor!", INPUT_FILE="Ulazna datoteka: ", OUTPUT_FILE="Izlazna datoteka: ", ENTER_PASSWORD="Lozinka: ", CONFIRM_PASSWORD="Potvrdite lozinku: ", PASSWORD_MISMATCH="Lozinke se ne podudaraju!", ENC_SUCCESS="Sifriranje uspjesno!", DEC_SUCCESS="Desifriranje uspjesno!", ENC_FAILED="Sifriranje neuspjesno: ", DEC_FAILED="Desifriranje neuspjesno: ", FILE_NOT_FOUND="Datoteka nije pronadena!", WRONG_PASS="Pogresna lozinka ili ostecena datoteka!", CONFIG_SAVED="Konfiguracija spremljena.", CONFIG_LOADED="Konfiguracija ucitana.", GOODBYE="Dovidenja!", PRESS_ENTER="Pritisnite Enter...", ERROR_PREFIX="Greska", LANG_PROMPT="Broj jezika (1-50): ", ENC_PROMPT="Sifriraj", DEC_PROMPT="Desifriraj", CONTACT_INFO="Kontakt: WeChat forever870422 / Email 810372789@qq.com", WELCOME_CONTRIB="Pomozite u prijevodu! forever870422")
add("bg", TITLE="=== Инструмент за Криптиране ===", SELECT_LANG="--- Изберете език ---", MAIN_MENU="--- Главно меню ---", ENCRYPT="1. Криптиране на файл", DECRYPT="2. Декриптиране на файл", CHANGE_LANG="3. Смяна на език", EXIT="4. Изход", ENTER_CHOICE="Въведете избор: ", INVALID_CHOICE="Невалиден избор!", INPUT_FILE="Входен файл: ", OUTPUT_FILE="Изходен файл: ", ENTER_PASSWORD="Парола: ", CONFIRM_PASSWORD="Потвърдете парола: ", PASSWORD_MISMATCH="Паролите не съвпадат!", ENC_SUCCESS="Криптирането успешно!", DEC_SUCCESS="Декриптирането успешно!", ENC_FAILED="Криптирането неуспешно: ", DEC_FAILED="Декриптирането неуспешно: ", FILE_NOT_FOUND="Файлът не е намерен!", WRONG_PASS="Грешна парола или повреден файл!", CONFIG_SAVED="Конфигурацията е запазена.", CONFIG_LOADED="Конфигурацията е заредена.", GOODBYE="Довиждане!", PRESS_ENTER="Натиснете Enter...", ERROR_PREFIX="Грешка", LANG_PROMPT="Номер на език (1-50): ", ENC_PROMPT="Криптиране", DEC_PROMPT="Декриптиране", CONTACT_INFO="Контакт: WeChat forever870422 / Email 810372789@qq.com", WELCOME_CONTRIB="Помогнете с превода! forever870422")

with open(path, 'w', encoding='utf-8') as f:
    json.dump(langs, f, ensure_ascii=False, indent=2)
print(f"FINAL: {len(langs)} languages saved!")
for i, (code, data) in enumerate(langs.items(), 1):
    print(f"  {i:2d}. {code:6s} - {data['TITLE'][:40]}")
