import json, os

path = r"C:\Users\邓涛\Documents\New project 3\file-crypto\src\lang_data.json"
with open(path, 'r', encoding='utf-8') as f:
    langs = json.load(f)

def add(code, **kw):
    langs[code] = kw

# 11-20
add("pt", TITLE="=== Ferramenta de Criptografia ===", SELECT_LANG="--- Selecionar Idioma ---", MAIN_MENU="--- Menu Principal ---", ENCRYPT="1. Criptografar arquivo", DECRYPT="2. Descriptografar arquivo", CHANGE_LANG="3. Mudar idioma", EXIT="4. Sair", ENTER_CHOICE="Digite sua opcao: ", INVALID_CHOICE="Opcao invalida!", INPUT_FILE="Arquivo de entrada: ", OUTPUT_FILE="Arquivo de saida: ", ENTER_PASSWORD="Senha: ", CONFIRM_PASSWORD="Confirmar senha: ", PASSWORD_MISMATCH="Senhas nao coincidem!", ENC_SUCCESS="Criptografia bem-sucedida!", DEC_SUCCESS="Descriptografia bem-sucedida!", ENC_FAILED="Falha na criptografia: ", DEC_FAILED="Falha na descriptografia: ", FILE_NOT_FOUND="Arquivo nao encontrado!", WRONG_PASS="Senha incorreta ou arquivo corrompido!", CONFIG_SAVED="Configuracao salva.", CONFIG_LOADED="Configuracao carregada.", GOODBYE="Adeus!", PRESS_ENTER="Pressione Enter...", ERROR_PREFIX="Erro", LANG_PROMPT="Numero do idioma (1-50): ", ENC_PROMPT="Criptografar", DEC_PROMPT="Descriptografar", CONTACT_INFO="Contato: WeChat forever870422 / Email 810372789@qq.com", WELCOME_CONTRIB="Ajude a traduzir! forever870422")
add("it", TITLE="=== Strumento di Cifratura ===", SELECT_LANG="--- Seleziona Lingua ---", MAIN_MENU="--- Menu Principale ---", ENCRYPT="1. Cifra file", DECRYPT="2. Decifra file", CHANGE_LANG="3. Cambia lingua", EXIT="4. Esci", ENTER_CHOICE="Inserisci scelta: ", INVALID_CHOICE="Scelta non valida!", INPUT_FILE="Percorso file input: ", OUTPUT_FILE="Percorso file output: ", ENTER_PASSWORD="Password: ", CONFIRM_PASSWORD="Conferma password: ", PASSWORD_MISMATCH="Le password non corrispondono!", ENC_SUCCESS="Cifratura riuscita!", DEC_SUCCESS="Decifratura riuscita!", ENC_FAILED="Cifratura fallita: ", DEC_FAILED="Decifratura fallita: ", FILE_NOT_FOUND="File non trovato!", WRONG_PASS="Password errata o file corrotto!", CONFIG_SAVED="Configurazione salvata.", CONFIG_LOADED="Configurazione caricata.", GOODBYE="Arrivederci!", PRESS_ENTER="Premi Enter...", ERROR_PREFIX="Errore", LANG_PROMPT="Numero lingua (1-50): ", ENC_PROMPT="Cifra", DEC_PROMPT="Decifra", CONTACT_INFO="Contatto: WeChat forever870422 / Email 810372789@qq.com", WELCOME_CONTRIB="Aiuta a tradurre! forever870422")
add("nl", TITLE="=== Bestand Versleuteling ===", SELECT_LANG="--- Kies Taal ---", MAIN_MENU="--- Hoofdmenu ---", ENCRYPT="1. Bestand versleutelen", DECRYPT="2. Bestand ontsleutelen", CHANGE_LANG="3. Taal wijzigen", EXIT="4. Afsluiten", ENTER_CHOICE="Voer keuze in: ", INVALID_CHOICE="Ongeldige keuze!", INPUT_FILE="Invoerbestand: ", OUTPUT_FILE="Uitvoerbestand: ", ENTER_PASSWORD="Wachtwoord: ", CONFIRM_PASSWORD="Bevestig wachtwoord: ", PASSWORD_MISMATCH="Wachtwoorden komen niet overeen!", ENC_SUCCESS="Versleuteling gelukt!", DEC_SUCCESS="Ontsleuteling gelukt!", ENC_FAILED="Versleuteling mislukt: ", DEC_FAILED="Ontsleuteling mislukt: ", FILE_NOT_FOUND="Bestand niet gevonden!", WRONG_PASS="Verkeerd wachtwoord of beschadigd bestand!", CONFIG_SAVED="Configuratie opgeslagen.", CONFIG_LOADED="Configuratie geladen.", GOODBYE="Tot ziens!", PRESS_ENTER="Druk op Enter...", ERROR_PREFIX="Fout", LANG_PROMPT="Taalnummer (1-50): ", ENC_PROMPT="Versleutelen", DEC_PROMPT="Ontsleutelen", CONTACT_INFO="Contact: WeChat forever870422 / Email 810372789@qq.com", WELCOME_CONTRIB="Help met vertalen! forever870422")
add("hi", TITLE="=== फ़ाइल एन्क्रिप्शन उपकरण ===", SELECT_LANG="--- भाषा चुनें ---", MAIN_MENU="--- मुख्य मेनू ---", ENCRYPT="1. फ़ाइल एन्क्रिप्ट करें", DECRYPT="2. फ़ाइल डिक्रिप्ट करें", CHANGE_LANG="3. भाषा बदलें", EXIT="4. बाहर निकलें", ENTER_CHOICE="अपनी पसंद दर्ज करें: ", INVALID_CHOICE="अमान्य विकल्प!", INPUT_FILE="इनपुट फ़ाइल: ", OUTPUT_FILE="आउटपुट फ़ाइल: ", ENTER_PASSWORD="पासवर्ड: ", CONFIRM_PASSWORD="पासवर्ड पुष्टि करें: ", PASSWORD_MISMATCH="पासवर्ड मेल नहीं खाते!", ENC_SUCCESS="एन्क्रिप्शन सफल!", DEC_SUCCESS="डिक्रिप्शन सफल!", ENC_FAILED="एन्क्रिप्शन विफल: ", DEC_FAILED="डिक्रिप्शन विफल: ", FILE_NOT_FOUND="फ़ाइल नहीं मिली!", WRONG_PASS="गलत पासवर्ड या दूषित फ़ाइल!", CONFIG_SAVED="कॉन्फ़िगरेशन सहेजा गया।", CONFIG_LOADED="कॉन्फ़िगरेशन लोड किया गया।", GOODBYE="अलविदा!", PRESS_ENTER="जारी रखने के लिए Enter दबाएं...", ERROR_PREFIX="त्रुटि", LANG_PROMPT="भाषा संख्या (1-50): ", ENC_PROMPT="एन्क्रिप्ट", DEC_PROMPT="डिक्रिप्ट", CONTACT_INFO="संपर्क: WeChat forever870422 / Email 810372789@qq.com", WELCOME_CONTRIB="अनुवाद में मदद करें! forever870422")
add("tr", TITLE="=== Dosya Sifreleme Araci ===", SELECT_LANG="--- Dil Secin ---", MAIN_MENU="--- Ana Menu ---", ENCRYPT="1. Dosyayi sifrele", DECRYPT="2. Dosyayi coz", CHANGE_LANG="3. Dil degistir", EXIT="4. Cikis", ENTER_CHOICE="Seciminizi girin: ", INVALID_CHOICE="Gecersiz secim!", INPUT_FILE="Girdi dosyasi: ", OUTPUT_FILE="Cikti dosyasi: ", ENTER_PASSWORD="Sifre: ", CONFIRM_PASSWORD="Sifreyi onaylayin: ", PASSWORD_MISMATCH="Sifreler eslesmiyor!", ENC_SUCCESS="Sifreleme basarili!", DEC_SUCCESS="Cozme basarili!", ENC_FAILED="Sifreleme basarisiz: ", DEC_FAILED="Cozme basarisiz: ", FILE_NOT_FOUND="Dosya bulunamadi!", WRONG_PASS="Yanlis sifre veya bozuk dosya!", CONFIG_SAVED="Yapilandirma kaydedildi.", CONFIG_LOADED="Yapilandirma yuklendi.", GOODBYE="Hoscakal!", PRESS_ENTER="Devam etmek icin Enter...", ERROR_PREFIX="Hata", LANG_PROMPT="Dil numarasi (1-50): ", ENC_PROMPT="Sifrele", DEC_PROMPT="Coz", CONTACT_INFO="Iletisim: WeChat forever870422 / Email 810372789@qq.com", WELCOME_CONTRIB="Ceviriye yardim edin! forever870422")
add("vi", TITLE="=== Cong cu Ma hoa/Giai ma ===", SELECT_LANG="--- Chon ngon ngu ---", MAIN_MENU="--- Menu Chinh ---", ENCRYPT="1. Ma hoa tap tin", DECRYPT="2. Giai ma tap tin", CHANGE_LANG="3. Doi ngon ngu", EXIT="4. Thoat", ENTER_CHOICE="Nhap lua chon: ", INVALID_CHOICE="Lua chon khong hop le!", INPUT_FILE="Tap tin dau vao: ", OUTPUT_FILE="Tap tin dau ra: ", ENTER_PASSWORD="Mat khau: ", CONFIRM_PASSWORD="Xac nhan mat khau: ", PASSWORD_MISMATCH="Mat khau khong khop!", ENC_SUCCESS="Ma hoa thanh cong!", DEC_SUCCESS="Giai ma thanh cong!", ENC_FAILED="Ma hoa that bai: ", DEC_FAILED="Giai ma that bai: ", FILE_NOT_FOUND="Khong tim thay tap tin!", WRONG_PASS="Sai mat khau hoac tap tin bi hong!", CONFIG_SAVED="Cau hinh da luu.", CONFIG_LOADED="Cau hinh da tai.", GOODBYE="Tam biet!", PRESS_ENTER="Nhan Enter de tiep tuc...", ERROR_PREFIX="Loi", LANG_PROMPT="So ngon ngu (1-50): ", ENC_PROMPT="Ma hoa", DEC_PROMPT="Giai ma", CONTACT_INFO="Lien he: WeChat forever870422 / Email 810372789@qq.com", WELCOME_CONTRIB="Giup dich thuat! forever870422")
add("th", TITLE="=== เครื่องมือเข้ารหัส/ถอดรหัส ===", SELECT_LANG="--- เลือกภาษา ---", MAIN_MENU="--- เมนูหลัก ---", ENCRYPT="1. เข้ารหัสไฟล์", DECRYPT="2. ถอดรหัสไฟล์", CHANGE_LANG="3. เปลี่ยนภาษา", EXIT="4. ออก", ENTER_CHOICE="ป้อนตัวเลือก: ", INVALID_CHOICE="ตัวเลือกไม่ถูกต้อง!", INPUT_FILE="ไฟล์นำเข้า: ", OUTPUT_FILE="ไฟล์ส่งออก: ", ENTER_PASSWORD="รหัสผ่าน: ", CONFIRM_PASSWORD="ยืนยันรหัสผ่าน: ", PASSWORD_MISMATCH="รหัสผ่านไม่ตรงกัน!", ENC_SUCCESS="เข้ารหัสสำเร็จ!", DEC_SUCCESS="ถอดรหัสสำเร็จ!", ENC_FAILED="เข้ารหัสล้มเหลว: ", DEC_FAILED="ถอดรหัสล้มเหลว: ", FILE_NOT_FOUND="ไม่พบไฟล์!", WRONG_PASS="รหัสผ่านผิดหรือไฟล์เสียหาย!", CONFIG_SAVED="บันทึกการตั้งค่าแล้ว", CONFIG_LOADED="โหลดการตั้งค่าแล้ว", GOODBYE="ลาก่อน!", PRESS_ENTER="กด Enter เพื่อดำเนินการต่อ...", ERROR_PREFIX="ข้อผิดพลาด", LANG_PROMPT="หมายเลขภาษา (1-50): ", ENC_PROMPT="เข้ารหัส", DEC_PROMPT="ถอดรหัส", CONTACT_INFO="ติดต่อ: WeChat forever870422 / Email 810372789@qq.com", WELCOME_CONTRIB="ช่วยแปลภาษา! forever870422")
add("pl", TITLE="=== Narzedzie Szyfrowania ===", SELECT_LANG="--- Wybierz jezyk ---", MAIN_MENU="--- Menu glowne ---", ENCRYPT="1. Zaszyfruj plik", DECRYPT="2. Odszyfruj plik", CHANGE_LANG="3. Zmien jezyk", EXIT="4. Wyjscie", ENTER_CHOICE="Wybierz opcje: ", INVALID_CHOICE="Nieprawidlowy wybor!", INPUT_FILE="Plik wejsciowy: ", OUTPUT_FILE="Plik wyjsciowy: ", ENTER_PASSWORD="Haslo: ", CONFIRM_PASSWORD="Potwierdz haslo: ", PASSWORD_MISMATCH="Hasla nie sa zgodne!", ENC_SUCCESS="Szyfrowanie udane!", DEC_SUCCESS="Odszyfrowanie udane!", ENC_FAILED="Szyfrowanie nieudane: ", DEC_FAILED="Odszyfrowanie nieudane: ", FILE_NOT_FOUND="Nie znaleziono pliku!", WRONG_PASS="Bledne haslo lub uszkodzony plik!", CONFIG_SAVED="Konfiguracja zapisana.", CONFIG_LOADED="Konfiguracja wczytana.", GOODBYE="Do widzenia!", PRESS_ENTER="Nacisnij Enter...", ERROR_PREFIX="Blad", LANG_PROMPT="Numer jezyka (1-50): ", ENC_PROMPT="Szyfruj", DEC_PROMPT="Odszyfruj", CONTACT_INFO="Kontakt: WeChat forever870422 / Email 810372789@qq.com", WELCOME_CONTRIB="Pomoz w tlumaczeniu! forever870422")
add("uk", TITLE="=== Інструмент шифрування ===", SELECT_LANG="--- Вибір мови ---", MAIN_MENU="--- Головне меню ---", ENCRYPT="1. Зашифрувати файл", DECRYPT="2. Розшифрувати файл", CHANGE_LANG="3. Змінити мову", EXIT="4. Вихід", ENTER_CHOICE="Введіть вибір: ", INVALID_CHOICE="Невірний вибір!", INPUT_FILE="Вхідний файл: ", OUTPUT_FILE="Вихідний файл: ", ENTER_PASSWORD="Пароль: ", CONFIRM_PASSWORD="Підтвердіть пароль: ", PASSWORD_MISMATCH="Паролі не збігаються!", ENC_SUCCESS="Шифрування успішне!", DEC_SUCCESS="Розшифрування успішне!", ENC_FAILED="Помилка шифрування: ", DEC_FAILED="Помилка розшифрування: ", FILE_NOT_FOUND="Файл не знайдено!", WRONG_PASS="Невірний пароль або пошкоджений файл!", CONFIG_SAVED="Конфігурацію збережено.", CONFIG_LOADED="Конфігурацію завантажено.", GOODBYE="До побачення!", PRESS_ENTER="Натисніть Enter...", ERROR_PREFIX="Помилка", LANG_PROMPT="Номер мови (1-50): ", ENC_PROMPT="Шифрувати", DEC_PROMPT="Розшифрувати", CONTACT_INFO="Контакт: WeChat forever870422 / Email 810372789@qq.com", WELCOME_CONTRIB="Допоможіть з перекладом! forever870422")
add("sv", TITLE="=== Filkrypteringsverktyg ===", SELECT_LANG="--- Valj sprak ---", MAIN_MENU="--- Huvudmeny ---", ENCRYPT="1. Kryptera fil", DECRYPT="2. Dekryptera fil", CHANGE_LANG="3. Byt sprak", EXIT="4. Avsluta", ENTER_CHOICE="Ange val: ", INVALID_CHOICE="Ogiltigt val!", INPUT_FILE="Infil: ", OUTPUT_FILE="Utfil: ", ENTER_PASSWORD="Losenord: ", CONFIRM_PASSWORD="Bekrafta losenord: ", PASSWORD_MISMATCH="Losenorden matchar inte!", ENC_SUCCESS="Kryptering lyckades!", DEC_SUCCESS="Dekryptering lyckades!", ENC_FAILED="Kryptering misslyckades: ", DEC_FAILED="Dekryptering misslyckades: ", FILE_NOT_FOUND="Filen hittades inte!", WRONG_PASS="Fel losenord eller skadad fil!", CONFIG_SAVED="Konfiguration sparad.", CONFIG_LOADED="Konfiguration laddad.", GOODBYE="Hej da!", PRESS_ENTER="Tryck Enter...", ERROR_PREFIX="Fel", LANG_PROMPT="Spraknummer (1-50): ", ENC_PROMPT="Kryptera", DEC_PROMPT="Dekryptera", CONTACT_INFO="Kontakt: WeChat forever870422 / Email 810372789@qq.com", WELCOME_CONTRIB="Hjalp till att oversatta! forever870422")

with open(path, 'w', encoding='utf-8') as f:
    json.dump(langs, f, ensure_ascii=False, indent=2)
print(f"Now have {len(langs)} languages")
